### ISSUE TITLE
Joystick.button to Joystick.setButton?

### ISSUE THREAD

**Issue by baritonomarchetto** [benjaminaigner/Joystick#1]
Hello Benjamin,
first of all: thanks for your work on this library!

Not an issue, but a request. May I ask you if it would be possible to turn Joystick.button to Joystick.setButton? This is because [Mattew Heironimus "well estabilished" arduino joystick library](https://github.com/MHeironimus/ArduinoJoystickLibrary) uses this nomenclature. I think that by adopting something more similar could help people that want to port arduino code to raspy pico.

just my 2 cents, thanks very much :)

**Comment by benjaminaigner** [comment]
Dear @baritonomarchetto 

THX for your interest in this library, I created a branch and quickly added the changes, see:
https://github.com/benjaminaigner/Joystick/tree/setButton

Please confirm this is working for you, than I can create a PR and merge it to master and create an update at Earl's arduino-pico core.

Greetings

**Comment by benjaminaigner** [comment]
Closed with #2 :+1:

**Comment by benjaminaigner** [comment]
Btw: I didn't update the arduino-pico repo, so if you want to use it right now, copy this library over the library in:
arduino->hardware/pico/rp2040/libraries/
