### ISSUE TITLE
Suggestion: Add ability to control number of Buttons/Axis/etc being reported

### ISSUE THREAD

**Issue by primis** [benjaminaigner/Joystick#3]
It would be nice if you could set the number of buttons / Other input types to be able to better emulate controllers. Steam for example, wont let you exit controller setup until you've mapped every button available to your controller.

**Comment by benjaminaigner** [comment]
Dear @primis ,

I'm thinking of a way to implement this,
unfortunately, this repo is not the right place for this request.

I've simply created an Arduino library to wrap the Gamepad interface of the TinyUSB library,
which is included by Earle Philhower in the arduino-pico core.

To change the number of buttons, the used axis and so on, it is necessary to:

* Change the HID report descriptor
* Change the HID report which is sent

Both functionalities are located in this repo:

https://github.com/adafruit/Adafruit_TinyUSB_Arduino

(which is included as a git submodule in the arduino-pico core).

Sorry I can't help you with this request.
