### ISSUE TITLE
How to change the HID name?

### ISSUE THREAD

**Issue by OrhanYigitDurmaz** [benjaminaigner/Joystick#5]
While used, pico appears as "PicoArduino". Searched everywhere for this to be nowhere found. I guess its hardcoded, but where?

**Comment by benjaminaigner** [comment]
Dear @OrhanYigitDurmaz ,

sorry for the late reply (was on holidays).
This string is set in the USB descriptor of your Arduino stack (can be differ if using either Earle's or Arduino's core).

It is hardcoded indeed, but not here.
A short search in files (```grep -nHIirF -- PicoArduino <arduino folder> ```)
turns out you can change the name in the file _RP2040USB.cpp_.

**Comment by OrhanYigitDurmaz** [comment]
> Dear @OrhanYigitDurmaz ,
> 
> sorry for the late reply (was on holidays). This string is set in the USB descriptor of your Arduino stack (can be differ if using either Earle's or Arduino's core).
> 
> It is hardcoded indeed, but not here. A short search in files (`grep -nHIirF -- PicoArduino <arduino folder> `) turns out you can change the name in the file _RP2040USB.cpp_.

Strange. When i look at the "RP2040USB.cpp file , icant find anything about "PicoArduino". Also GitHub search doesnt work.

**Comment by benjaminaigner** [comment]
You are right, since last time it has changed.

It is much easier now:

open the `boards.txt` file and change the `usb_product` string for your board, e.g.:

`arduino_nano_connect.build.usb_product="A different name"`

**Comment by OrhanYigitDurmaz** [comment]
Dear @benjaminaigner 

Sadly, that also doesnt work. boards.txt only have "Pico" as the usb_product and changing it had no effect.

Update: Strange, Zadig (USB Driver installation tool) sees the new name. When i encountered this issue on the Pico SDK, changing vid/pid to Arduino MCUs "32u4" worked. Let me try that.

Update 2:  Yeah that worked. I dont know what happens to cause this, but using the default PID/VID from the core doesnt seem to change the name. Probably something windows related.

Also can i ask to update the library to 12 bits? That would be very helpful.

Anyways, thanks for the help!
