### ISSUE TITLE
hat is incorrectly mapped

### ISSUE THREAD

**Issue by tommybee456** [benjaminaigner/Joystick#6]
Pulled my hair out for a bit trying to get the hat to work correctly haha. You have it mapped like this
```c++
void Joystick_::hat(int angle)
{
	if(angle < 0) data.hat = 0;
	if(angle >= 0 && angle <= 360) data.hat = map(angle,0,360,1,8);
	if(_autosend) send_now();
}
``` 
when is should be mapped like this: 
```c++
void Joystick_::hat(int angle)
{
	if(angle < 0) data.hat = 0;
	if(angle >= 0 && angle <= 360) data.hat = map(angle,0,360,1,9);
	if(_autosend) send_now();
}
``` 
and if you wanted you could add something like this

```c++
void Joystick_::hat(int angle)
{
	if(angle < 0) data.hat = 0;
	if(angle >= 0 && angle <= 360) data.hat = map(angle,0,360,1,9);
        if(data.hat == 9) data.hat = 0;
	if(_autosend) send_now();
}
``` 

Basically the reason it needs to be mapped to 9 is because there are 8 positions but 360 degrees would be a 9th position since it wraps back to 0. Otherwise 360 degrees points up and left when it should point up. This way now every position is separated by 45 degrees. Honestly in my opinion I would just get rid of the angle stuff and have the function work with inputs from 1-8 (or 0-7 it doesn't matter) with -1 being neutral.

**Comment by benjaminaigner** [comment]
Dear @tommybee456 ,
uuuuhhh, you are right, I'll replace you the lost hair :-).

For compatibility reasons, I shouldn't replace the angle function, but we can arrange maybe an overloaded function with an enum for the position?

**Comment by benjaminaigner** [comment]
Dear @tommybee456 ,

I've fixed the angle function & added an enum (see https://github.com/benjaminaigner/Joystick/tree/hat_enum )
Is this what you expect?

I've attached a test sketch (please rename to .ino, GH only allows .txt).
[hat.txt](https://github.com/benjaminaigner/Joystick/files/15091598/hat.txt)

**Comment by tommybee456** [comment]
Hey, yea that works and makes sense. Thanks!

**Comment by benjaminaigner** [comment]
OK, is merged to master. I'll inform Earle to have it included in arduino-pico.
Thx for reporting!
